# Generated by Django 3.2.4 on 2021-07-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='special_offers',
            field=models.BooleanField(default=False),
        ),
    ]
