# Generated by Django 3.2.4 on 2021-11-03 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='town',
            new_name='area',
        ),
    ]
