# Generated by Django 3.2.4 on 2021-07-01 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_preorderingcalender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorderingcalender',
            name='item_id',
        ),
    ]
