# Generated by Django 3.2.4 on 2021-11-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_town_address_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethods',
            options={'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AddField(
            model_name='address',
            name='delivery_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
