# Generated by Django 3.2.4 on 2021-11-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211104_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='delivery_type',
        ),
        migrations.AddField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
