# Generated by Django 3.2.4 on 2021-11-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211104_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='instruction',
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
