# Generated by Django 3.2.4 on 2021-11-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211104_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
