# Generated by Django 3.2.4 on 2021-07-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='recipe_category/')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='recipe_images/')),
                ('no_of_consumers', models.IntegerField(default=1)),
                ('nutritional_details', models.CharField(max_length=100000)),
                ('min_duration', models.IntegerField()),
                ('max_duration', models.IntegerField()),
                ('attribution', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100000)),
                ('ingredient', models.CharField(max_length=100000)),
                ('allergies', models.CharField(max_length=100000)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('vid_instruction', models.FileField(upload_to='video_instructions/')),
                ('text_instruction', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20000)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20000)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
