# Generated by Django 3.2.4 on 2021-11-02 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sche_recipes', to='recipe.recipe'),
        ),
        migrations.AddField(
            model_name='scheduledrecipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sche_recipes_fu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_saves', to='recipe.recipe'),
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='all_ratings',
            field=models.ManyToManyField(blank=True, null=True, to='recipe.Rating'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipe.category'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='raters',
            field=models.ManyToManyField(blank=True, null=True, related_name='rated_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='raters_ids',
            field=models.ManyToManyField(blank=True, null=True, related_name='r', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='recipe.Review'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tips_from_chef',
            field=models.ManyToManyField(blank=True, null=True, to='recipe.Tip'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
