# Generated by Django 3.2.4 on 2021-07-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text_instruction',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='vid_instruction',
            field=models.FileField(blank=True, null=True, upload_to='video_instructions/'),
        ),
    ]
