# Generated by Django 3.2.4 on 2021-07-02 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0004_recipe_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='raters_ids',
            field=models.ManyToManyField(blank=True, null=True, related_name='r', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='raters',
            field=models.ManyToManyField(blank=True, null=True, related_name='rated_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_saves', to='recipe.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
