# Generated by Django 3.2.4 on 2021-11-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_alter_recipe_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='attribution',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutritional_details',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
