# Generated by Django 3.2.4 on 2021-07-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20210702_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=1),
        ),
    ]
