# Generated by Django 3.2.4 on 2021-11-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20211103_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='nutritional_details',
        ),
    ]
