# Generated by Django 3.2.4 on 2021-11-03 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20211103_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionalfact',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutri_details', to='recipe.recipe'),
        ),
    ]
