# Generated by Django 3.2.4 on 2021-11-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_nutritionalfact_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
