# Generated by Django 3.2.4 on 2021-10-28 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0010_recipe_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_to_order', models.DateField()),
                ('date', models.DateTimeField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sche_recipes', to='recipe.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sche_recipes_fu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
