# Generated by Django 3.2.4 on 2021-10-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_scheduledrecipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledrecipes',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
