# Generated by Django 3.2.4 on 2021-11-03 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_recipe', to='recipe.event'),
        ),
    ]
