# Generated by Django 3.2.4 on 2021-10-28 10:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0012_alter_scheduledrecipes_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduledRecipes',
            new_name='ScheduledRecipe',
        ),
    ]
