# Generated by Django 3.2.4 on 2021-10-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_rename_scheduledrecipes_scheduledrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledrecipe',
            name='date_to_order',
            field=models.CharField(max_length=20),
        ),
    ]
