# Generated by Django 3.2.4 on 2021-07-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0001_initial'),
        ('glocery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glocery',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='recipe.Review'),
        ),
    ]
