# Generated by Django 3.2.4 on 2021-11-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glocery', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glocery',
            name='image',
            field=models.ImageField(upload_to='images/recipe_images/'),
        ),
        migrations.AlterField(
            model_name='glocerycategory',
            name='image',
            field=models.ImageField(upload_to='images/glocery_category/'),
        ),
    ]
