# Generated by Django 3.2.4 on 2021-07-02 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glocery', '0002_glocery_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glocery',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gloceries', to='glocery.category'),
        ),
    ]
