# Generated by Django 3.2.4 on 2021-07-01 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('glocery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='glocery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glocery.glocery'),
        ),
    ]
