# Generated by Django 3.2.4 on 2021-07-01 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_orderitem_glocery'),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='cart.OrderItem'),
        ),
    ]
